function norm(v){return String(v||'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function cleanLines(text){return String(text||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).slice(0,80)}
function pokemonPrice(card){const cp=card?.cardmarket?.prices||{};if(Number.isFinite(cp.avg7))return{label:'Cardmarket 7-day average',amount:cp.avg7,currency:'EUR',updatedAt:card.cardmarket.updatedAt||''};if(Number.isFinite(cp.trendPrice))return{label:'Cardmarket trend',amount:cp.trendPrice,currency:'EUR',updatedAt:card.cardmarket.updatedAt||''};const groups=Object.values(card?.tcgplayer?.prices||{});const market=groups.map(x=>x?.market).find(Number.isFinite);if(Number.isFinite(market))return{label:'TCGplayer market',amount:market,currency:'USD',updatedAt:card.tcgplayer.updatedAt||''};return null}
function usefulNames(lines){const bad=/^(basic|stage|trainer|supporter|item|stadium|energy|pokemon|pokémon|spell card|trap card|effect|normal|quick-play|continuous|field|ritual|equip|hp\s*\d+|atk|def|illus\.|weakness|resistance|retreat|ability|rule|once during|you may|your turn)/i;return [...new Set(lines.filter(x=>x.length>=3&&x.length<=38&&!bad.test(x)&&/[a-z]/i.test(x)&&!/^\d+[\/\-]\d+$/i.test(x)&&!/^\d+$/.test(x)))].slice(0,10)}
function pokemonNumber(text){const m=String(text).match(/\b(\d{1,3})\s*\/\s*\d{1,3}\b/);return m?m[1]:''}
function ygoSetCode(text){const m=String(text).match(/\b([A-Z0-9]{2,8}-[A-Z]{0,3}\d{1,4})\b/i);return m?m[1].toUpperCase():''}
async function pokeSearch(query,headers){const r=await fetch(`https://api.pokemontcg.io/v2/cards?q=${encodeURIComponent(query)}&pageSize=30`,{headers});const d=await r.json().catch(()=>({}));return r.ok&&Array.isArray(d.data)?d.data:[]}
function pokeScore(card,text,num,nameHint){const ntext=norm(text);let s=0;if(nameHint&&norm(card.name)===norm(nameHint))s+=100;if(ntext.includes(norm(card.name)))s+=120;if(num&&String(card.number).replace(/\D/g,'')===String(num).replace(/\D/g,''))s+=100;if(card.set?.name&&ntext.includes(norm(card.set.name)))s+=35;return s}
async function lookupPokemon(text,lines){const headers={};if(process.env.POKEMON_TCG_API_KEY)headers['X-Api-Key']=process.env.POKEMON_TCG_API_KEY;const num=pokemonNumber(text),names=usefulNames(lines);let best=null,bestScore=-1;for(const name of names.slice(0,6)){const qs=[];if(num)qs.push(`name:\"${name.replace(/\"/g,'')}\" number:${num}`);qs.push(`name:\"${name.replace(/\"/g,'')}\"`);for(const q of qs){const cards=await pokeSearch(q,headers);for(const card of cards){const sc=pokeScore(card,text,num,name);if(sc>bestScore){best=card;bestScore=sc}}if(bestScore>=200)break}if(bestScore>=200)break}if(!best||bestScore<115)return null;return{game:'Pokémon',name:best.name,setName:best.set?.name||'',number:best.number||'',rarity:best.rarity||'',image:best.images?.large||best.images?.small||'',price:pokemonPrice(best),matchScore:bestScore}}
function ygoScore(card,text,setCode,nameHint){const ntext=norm(text);let s=0;if(nameHint&&norm(card.name)===norm(nameHint))s+=100;if(ntext.includes(norm(card.name)))s+=120;const sets=card.card_sets||[];if(setCode&&sets.some(x=>norm(x.set_code)===norm(setCode)))s+=140;return s}
async function lookupYgo(text,lines){const setCode=ygoSetCode(text),names=usefulNames(lines);let best=null,bestSet=null,bestScore=-1;for(const name of names.slice(0,6)){const r=await fetch(`https://db.ygoprodeck.com/api/v7/cardinfo.php?fname=${encodeURIComponent(name)}`);const d=await r.json().catch(()=>({}));if(!r.ok||!Array.isArray(d.data))continue;for(const card of d.data){const sc=ygoScore(card,text,setCode,name);if(sc>bestScore){best=card;bestScore=sc;bestSet=(card.card_sets||[]).find(x=>norm(x.set_code)===norm(setCode))||(card.card_sets||[])[0]||null}}if(bestScore>=220)break}if(!best||bestScore<115)return null;const p=(best.card_prices||[])[0]||{},eur=parseFloat(p.cardmarket_price),usd=parseFloat(p.tcgplayer_price);const price=Number.isFinite(eur)&&eur>0?{label:'Cardmarket reference',amount:eur,currency:'EUR',updatedAt:''}:Number.isFinite(usd)&&usd>0?{label:'TCGplayer reference',amount:usd,currency:'USD',updatedAt:''}:null;return{game:'Yu-Gi-Oh!',name:best.name,setName:bestSet?.set_name||'',number:bestSet?.set_code||setCode||'',rarity:bestSet?.set_rarity||'',image:best.card_images?.[0]?.image_url||'',price,matchScore:bestScore}}
export default async function handler(req,res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','POST,OPTIONS');if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST')return res.status(405).json({error:'POST only'});try{const text=String(req.body?.text||'').trim();if(text.length<3)return res.status(400).json({error:'No card text found. Hold the card flat and fill the frame.'});const lines=cleanLines(text);const looksYgo=/\b(atk|def|spell card|trap card|duelist|konami)\b/i.test(text)||!!ygoSetCode(text);const looksPokemon=/\b(hp\s*\d+|basic|stage\s*[12]|weakness|retreat|trainer|pokémon|pokemon)\b/i.test(text)||!!pokemonNumber(text);let card=null;if(looksYgo&&!looksPokemon)card=await lookupYgo(text,lines);else if(looksPokemon&&!looksYgo)card=await lookupPokemon(text,lines);else{const [p,y]=await Promise.all([lookupPokemon(text,lines).catch(()=>null),lookupYgo(text,lines).catch(()=>null)]);card=(p?.matchScore||0)>=(y?.matchScore||0)?p:y}if(!card)return res.status(404).json({error:'Card not recognised. Move closer, avoid glare and scan again.'});delete card.matchScore;const easter=/^magikarp$/i.test(card.name||'');return res.status(200).json({card,easterEgg:easter?'magikarp':null,mode:'on-device-ocr'});}catch(err){console.error('tattie-scan',err);return res.status(500).json({error:'Could not match that card. Scan it again in good light.'})}}
