import React,{useEffect,useRef,useState}from'react';
import{SafeAreaView,View,Text,Pressable,ScrollView,TextInput,StyleSheet,Alert,Image,ActivityIndicator,Linking}from'react-native';
import{StatusBar}from'expo-status-bar';
import{CameraView,useCameraPermissions}from'expo-camera';
import*as Speech from'expo-speech';
import AsyncStorage from'@react-native-async-storage/async-storage';
import QRCode from'react-native-qrcode-svg';
import{Ionicons}from'@expo/vector-icons';
import{localAnswer,extractName}from'./tattieKnowledge';
import{askWeeTattie}from'./weeTattieAgent';

const P='#b026ff',BG='#050309',CARD='#120b18',LINE='#3a2148',M='#b8a9c4',W='#fff',GREEN='#42ff7a';
const SCAN_API='https://xp-ai-interface.vercel.app/api/tattie/scan';
const SHOP='https://tattie-tcg.myshopify.com';
const APK='https://xp-ai-interface.vercel.app/api/tattie/download';
const PROFILE_KEY='tattie_profile_v1';
let maleVoice=null;
const speak=async t=>{Speech.stop();try{if(!maleVoice){const vs=await Speech.getAvailableVoicesAsync();const en=vs.filter(v=>String(v.language||'').toLowerCase().startsWith('en'));const males=en.filter(v=>/male|gbb|gbm|uk.*m/i.test(String(v.name||'')+' '+String(v.identifier||'')));maleVoice=(males.find(v=>String(v.language||'').toLowerCase().includes('gb'))||males[0]||en.find(v=>String(v.language||'').toLowerCase().includes('gb'))||{}).identifier||null}Speech.speak(String(t),{language:'en-GB',voice:maleVoice||undefined,rate:.9,pitch:.78})}catch{Speech.speak(String(t),{language:'en-GB',rate:.9,pitch:.78})}};

function Btn({children,onPress,outline=false}){return <Pressable onPress={onPress} style={[s.btn,outline&&s.btnOutline]}><Text style={s.btnText}>{children}</Text></Pressable>}
function Header({title}){return <View style={s.header}><Image source={require('../assets/tattie-logo.jpg')} style={s.logo} resizeMode="contain"/><Text style={s.headerTitle}>{title}</Text></View>}

function Home({go}){return <View style={s.exactHome}>
  <Image source={require('../assets/home-screen-exact.png')} style={s.exactHomeImage} resizeMode="stretch"/>
  <Pressable accessibilityLabel="Talk to Wee Tattie" onPress={()=>go('tattie')} style={[s.hit,{left:'0%',top:'0%',width:'100%',height:'35.5%'}]}/>
  <Pressable accessibilityLabel="Card Scanner" onPress={()=>go('scanner')} style={[s.hit,{left:'0%',top:'35.5%',width:'100%',height:'12%'}]}/>
  <Pressable accessibilityLabel="Shop" onPress={()=>go('shop')} style={[s.hit,{left:'0%',top:'47.5%',width:'50%',height:'13.5%'}]}/>
  <Pressable accessibilityLabel="Community" onPress={()=>go('community')} style={[s.hit,{left:'50%',top:'47.5%',width:'50%',height:'13.5%'}]}/>
  <Pressable accessibilityLabel="Home" onPress={()=>go('home')} style={[s.hit,{left:'0%',top:'89%',width:'20%',height:'11%'}]}/>
  <Pressable accessibilityLabel="Scanner" onPress={()=>go('scanner')} style={[s.hit,{left:'20%',top:'89%',width:'20%',height:'11%'}]}/>
  <Pressable accessibilityLabel="Shop" onPress={()=>go('shop')} style={[s.hit,{left:'40%',top:'89%',width:'20%',height:'11%'}]}/>
  <Pressable accessibilityLabel="Community" onPress={()=>go('community')} style={[s.hit,{left:'60%',top:'89%',width:'20%',height:'11%'}]}/>
  <Pressable accessibilityLabel="Menu" onPress={()=>go('menu')} style={[s.hit,{left:'80%',top:'89%',width:'20%',height:'11%'}]}/>
</View>}

function Tattie(){const[msg,setMsg]=useState([{role:'assistant',content:"Aye legend! I’m Wee Tattie. Pokémon, Yu-Gi-Oh!, collecting, card care or just a blether — fire away."}]);const[text,setText]=useState('');const[busy,setBusy]=useState(false);const[profile,setProfile]=useState({});useEffect(()=>{AsyncStorage.getItem(PROFILE_KEY).then(v=>{if(v)setProfile(JSON.parse(v))}).catch(()=>{})},[]);const send=async()=>{const value=text.trim();if(!value||busy)return;const before=[...msg];setMsg([...before,{role:'user',content:value}]);setText('');const name=extractName(value);if(name){const next={...profile,name};setProfile(next);AsyncStorage.setItem(PROFILE_KEY,JSON.stringify(next)).catch(()=>{});const r=`Nice to meet ye, ${name}. I'll mind your name on this phone. 🥔`;setMsg(m=>[...m,{role:'assistant',content:r}]);speak(r);return}const local=localAnswer(value);if(local){setMsg(m=>[...m,{role:'assistant',content:local}]);speak(local);return}setBusy(true);try{const r=await askWeeTattie({message:value,history:before.slice(-10),profile});setMsg(m=>[...m,{role:'assistant',content:r}]);speak(r)}catch{const r='I’m having trouble connecting just now. Try again in a moment.';setMsg(m=>[...m,{role:'assistant',content:r}]);speak(r)}finally{setBusy(false)}};return <ScrollView contentContainerStyle={s.page}><Header title="WEE TATTIE AI"/><Image source={require('../assets/wee-tattie-home.jpg')} style={s.agentImg} resizeMode="cover"/>{msg.map((m,i)=><View key={i} style={[s.chat,m.role==='user'&&s.chatUser]}><Text style={s.body}>{m.content}</Text></View>)}{busy&&<ActivityIndicator color={P}/>}<View style={s.inputRow}><TextInput style={s.input} value={text} onChangeText={setText} placeholder="Talk to Wee Tattie…" placeholderTextColor={M} onSubmitEditing={send}/><Pressable onPress={send} style={s.send}><Ionicons name="send" size={20} color={W}/></Pressable></View></ScrollView>}

function Scanner(){const[permission,requestPermission]=useCameraPermissions();const cam=useRef(null);const[photo,setPhoto]=useState(null);const[result,setResult]=useState(null);const[busy,setBusy]=useState(false);if(!permission)return <View style={s.center}><Text style={s.body}>Loading camera…</Text></View>;if(!permission.granted)return <View style={s.center}><Header title="CARD SCANNER"/><Text style={s.body}>Allow camera access so Wee Tattie can scan your card.</Text><Btn onPress={requestPermission}>ALLOW CAMERA</Btn></View>;const reset=()=>{setPhoto(null);setResult(null)};const snap=async()=>{if(busy)return;setBusy(true);try{const p=await cam.current?.takePictureAsync({quality:.45,base64:true});if(!p?.base64)throw new Error();setPhoto(p.uri);const r=await fetch(SCAN_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:`data:image/jpeg;base64,${p.base64}`})});const d=await r.json();if(!r.ok||!d.card)throw new Error();setResult(d.card);if(d.easterEgg==='magikarp')Alert.alert('LEGENDARY PULL DETECTED…','Oh wait… it’s just a Magikarp 😂')}catch{Alert.alert('Scanner','Couldn’t identify this card. Try again with the card flat and clearly visible.')}finally{setBusy(false)}};return <ScrollView contentContainerStyle={s.page}><Header title="CARD SCANNER"/>{!photo?<View style={s.cameraShell}><CameraView ref={cam} style={s.camera} facing="back"/><View pointerEvents="none" style={s.scanFrame}/><Pressable onPress={snap} style={s.shutter}><Ionicons name="camera" size={30} color={W}/></Pressable></View>:<Image source={{uri:result?.image||photo}} style={s.preview} resizeMode="contain"/>}{busy&&<ActivityIndicator color={P}/>} {result&&<View style={s.resultCard}><Text style={s.resultName}>{result.name}</Text><Text style={s.body}>{result.setName||''} {result.number||''}</Text>{result.price&&<Text style={s.price}>{result.price.currency==='EUR'?'€':'$'}{Number(result.price.amount).toFixed(2)}</Text>}<Btn outline onPress={reset}>SCAN ANOTHER CARD</Btn></View>}</ScrollView>}

function Shop(){return <ScrollView contentContainerStyle={s.page}><Header title="SHOP"/><Text style={s.body}>Pokémon, Yu-Gi-Oh!, graded cards and sealed products.</Text><Btn onPress={()=>Linking.openURL(SHOP)}>OPEN LIVE TATTIE SHOP</Btn></ScrollView>}
function Community(){const[text,setText]=useState('');const[msgs,setMsgs]=useState(['Welcome to the Tattie crew 🥔🔥']);return <View style={s.pageFlex}><Header title="COMMUNITY"/><ScrollView style={{flex:1}}>{msgs.map((m,i)=><View key={i} style={s.chat}><Text style={s.body}>{m}</Text></View>)}</ScrollView><View style={s.inputRow}><TextInput style={s.input} value={text} onChangeText={setText} placeholder="Message community" placeholderTextColor={M}/><Pressable onPress={()=>{if(text.trim()){setMsgs(v=>[...v,text.trim()]);setText('')}}} style={s.send}><Ionicons name="send" size={20} color={W}/></Pressable></View></View>}
function Menu({go}){return <ScrollView contentContainerStyle={s.page}><Header title="MENU"/>{['My Collection','Wishlist','Price Alerts','Trade List'].map(x=><Pressable key={x} style={s.menuLine} onPress={()=>Alert.alert(x,'This section is ready for your saved collection data.')}><Text style={s.body}>{x}</Text></Pressable>)}<Btn onPress={()=>go('tattie')}>TALK TO WEE TATTIE AI</Btn><Btn outline onPress={()=>go('qr')}>QR DOWNLOAD</Btn><Btn outline onPress={()=>Linking.openURL(APK)}>CHECK FOR APP UPDATE</Btn></ScrollView>}
function QR(){return <ScrollView contentContainerStyle={[s.page,{alignItems:'center'}]}><Header title="GET THE APP"/><Text style={s.body}>Scan this QR code for the current official APK.</Text><View style={s.qr}><QRCode value={APK} size={220}/></View><Btn onPress={()=>Linking.openURL(APK)}>DOWNLOAD APK</Btn></ScrollView>}

export default function App(){const[screen,setScreen]=useState('home');if(screen==='home')return <View style={s.safe}><StatusBar hidden/><Home go={setScreen}/></View>;const pages={scanner:<Scanner/>,shop:<Shop/>,community:<Community/>,menu:<Menu go={setScreen}/>,tattie:<Tattie/>,qr:<QR/>};const special=['tattie','qr'].includes(screen);const tabs=[['home','home','Home'],['scanner','scan','Scanner'],['shop','bag-handle','Shop'],['community','people','Community'],['menu','menu','Menu']];return <SafeAreaView style={s.safe}><StatusBar style="light"/><View style={{flex:1}}>{pages[screen]}</View>{special?<View style={s.backDock}><Btn onPress={()=>setScreen('home')}>‹ BACK HOME</Btn></View>:<View style={s.nav}>{tabs.map(t=><Pressable key={t[0]} onPress={()=>setScreen(t[0])} style={s.navItem}><Ionicons name={t[1]} size={20} color={screen===t[0]?P:M}/><Text style={[s.navText,screen===t[0]&&{color:P}]}>{t[2]}</Text></Pressable>)}</View>}</SafeAreaView>}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:BG},exactHome:{flex:1,backgroundColor:BG,position:'relative',overflow:'hidden'},exactHomeImage:{position:'absolute',top:0,left:0,right:0,bottom:0,width:'100%',height:'100%'},hit:{position:'absolute',backgroundColor:'transparent'},page:{padding:16,paddingBottom:34,gap:14,backgroundColor:BG},pageFlex:{flex:1,padding:16,gap:14,backgroundColor:BG},center:{flex:1,backgroundColor:BG,padding:20,justifyContent:'center',gap:16},header:{minHeight:62,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},logo:{width:158,height:56,borderRadius:10},headerTitle:{color:W,fontSize:18,fontWeight:'900'},btn:{minHeight:48,borderRadius:15,backgroundColor:P,alignItems:'center',justifyContent:'center',paddingHorizontal:18},btnOutline:{backgroundColor:'transparent',borderWidth:1.5,borderColor:P},btnText:{color:W,fontWeight:'900'},body:{color:W,fontSize:15,lineHeight:21},agentImg:{width:'100%',height:280,borderRadius:22},chat:{alignSelf:'flex-start',maxWidth:'88%',backgroundColor:'#17101f',borderRadius:17,padding:12,borderWidth:1,borderColor:'#352340',marginBottom:8},chatUser:{alignSelf:'flex-end',backgroundColor:'#56117d',borderColor:P},inputRow:{flexDirection:'row',gap:8,alignItems:'center'},input:{flex:1,minHeight:50,borderWidth:1,borderColor:LINE,borderRadius:14,backgroundColor:'#0c0711',color:W,paddingHorizontal:14,fontSize:15},send:{width:50,height:50,borderRadius:16,backgroundColor:P,alignItems:'center',justifyContent:'center'},cameraShell:{height:480,borderRadius:24,overflow:'hidden',backgroundColor:'#000'},camera:{flex:1},scanFrame:{position:'absolute',left:34,right:34,top:55,bottom:90,borderWidth:3,borderColor:P,borderRadius:18},shutter:{position:'absolute',bottom:20,left:'43%',width:58,height:58,borderRadius:29,backgroundColor:P,alignItems:'center',justifyContent:'center'},preview:{height:440,width:'100%',borderRadius:22,backgroundColor:'#111'},resultCard:{borderWidth:1,borderColor:LINE,borderRadius:20,backgroundColor:CARD,padding:15,gap:10},resultName:{color:W,fontWeight:'900',fontSize:25},price:{color:GREEN,fontSize:28,fontWeight:'900'},menuLine:{minHeight:55,borderBottomWidth:1,borderBottomColor:LINE,justifyContent:'center'},qr:{backgroundColor:W,padding:16,borderRadius:16},nav:{height:82,paddingBottom:16,borderTopWidth:1,borderTopColor:'#2a1a33',backgroundColor:'#09060c',flexDirection:'row'},navItem:{flex:1,alignItems:'center',justifyContent:'center',gap:3},navText:{fontSize:9,color:M},backDock:{paddingHorizontal:10,paddingTop:10,paddingBottom:22,borderTopWidth:1,borderTopColor:LINE,backgroundColor:'#09060c'}});
