const caption=document.getElementById('caption'),options=document.getElementById('options'),panel=document.getElementById('panel'),title=document.getElementById('panelTitle'),body=document.getElementById('panelBody');
const input=document.getElementById('coreInput'),send=document.getElementById('send'),chatState=document.getElementById('chatState');let cameraStream=null;
const templates={modes:`<div class="control"><label>ACTIVE MODE</label><select id="mode"><option>Idle</option><option>Engineering</option><option>Boat</option><option>Camping</option><option>Exploration</option><option>Thinking</option><option>Listening</option><option>Alert</option></select></div>`,memory:`<div class="control"><label>COMMAND CENTER NOTES</label><textarea id="memory" placeholder="Local command-center notes"></textarea><button onclick="save('memory')">SAVE</button></div>`,voice:`<div class="control"><label>VOICE</label><button onclick="startVoice()">TALK TO XP</button><div id="voiceStatus">Ready</div></div>`,vision:`<div class="control"><label>VISION</label><button onclick="startCamera()">START LIVE CAMERA</button><button onclick="stopCamera()">STOP CAMERA</button></div>`,text:`<div class="control"><label>LIVE XP CORE</label><textarea id="textInput" placeholder="Talk to XP..."></textarea><button onclick="sendPanelText()">SEND TO XP</button></div>`,settings:`<div class="control"><label>COMMAND CENTER</label><div>Core: http://127.0.0.1:8765</div><div>Telemetry: live</div><div>Camera: local device</div></div>`,system:`<div class="control"><label>MOTHERSHIP</label><div id="sysPanel">Reading live systems…</div></div>`};
function setCaption(v){caption.textContent=v}window.setCaption=setCaption;
function save(k){localStorage.setItem('xp-'+k,document.getElementById(k)?.value||'');setCaption('SAVED')}window.save=save;
function fmtUp(s){s=Number(s)||0;const d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60);return `${d}d ${h}h ${m}m`}
async function refresh(){try{const t=await window.xpDesktop.telemetry();cpu.textContent=t.cpu+'%';ram.textContent=t.ram+'%';disk.textContent=t.disk+'%';uptime.textContent=fmtUp(t.uptime);processes.innerHTML=t.processes.map(x=>`<div>${x}</div>`).join('');status.textContent=t.core.online?'● XP CORE ONLINE':'● XP CORE OFFLINE';status.style.color=t.core.online?'#63f7a4':'#ff5c7a';systemInfo.innerHTML=`XP Core: <b>${t.core.online?'ONLINE':'OFFLINE'}</b><br>Windows telemetry: LIVE<br>Command bridge: ACTIVE`; }catch(e){systemInfo.textContent='Telemetry unavailable: '+e.message}}
async function sendMessage(v){v=(v||'').trim();if(!v)return;send.disabled=true;chatState.textContent=' // THINKING';setCaption('XP THINKING');try{const r=await window.xpDesktop.chat(v);setCaption(r.ok?'XP: '+String(r.reply).slice(0,120):'CORE ERROR');chatState.textContent=r.ok?' // REPLY RECEIVED':' // ERROR';}catch(e){chatState.textContent=' // ERROR';setCaption('XP CORE ERROR');}finally{send.disabled=false;input.focus();}}
send.onclick=()=>{const v=input.value;input.value='';sendMessage(v)};input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();send.click()}});
window.sendPanelText=()=>{const e=document.getElementById('textInput');if(e){sendMessage(e.value);e.value=''}};
document.querySelectorAll('[data-url]').forEach(b=>b.onclick=()=>window.xpDesktop.openUrl(b.dataset.url));
window.startCamera=async()=>{try{if(cameraStream)return;cameraStream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});camera.srcObject=cameraStream;setCaption('LIVE CAMERA ACTIVE')}catch(e){setCaption('CAMERA: '+e.message)}};
window.stopCamera=()=>{if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null;camera.srcObject=null;}setCaption('CAMERA STOPPED')};
cameraOn.onclick=window.startCamera;cameraOff.onclick=window.stopCamera;snapshot.onclick=()=>setCaption(cameraStream?'LIVE CAMERA READY FOR SNAPSHOT':'START CAMERA FIRST');
attach.onclick=async()=>{const p=await window.xpDesktop.chooseImage();if(p){localStorage.setItem('xp-last-image',p);setCaption('IMAGE ATTACHED: '+p.split(/[\\/]/).pop());}};
window.startVoice=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setCaption('VOICE INPUT NOT AVAILABLE');return;}const r=new SR();r.lang='en-GB';r.interimResults=false;r.onstart=()=>setCaption('XP LISTENING');r.onresult=e=>{const v=e.results[0][0].transcript;input.value=v;sendMessage(v)};r.onerror=e=>setCaption('VOICE: '+e.error);r.start()};
document.getElementById('brainButton').onclick=()=>options.classList.toggle('hidden');document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=async()=>{const k=b.dataset.panel;title.textContent=k.toUpperCase();body.innerHTML=templates[k];panel.classList.remove('hidden');options.classList.add('hidden');if(k==='memory'){memory.value=localStorage.getItem('xp-memory')||''}if(k==='modes'){mode.value=localStorage.getItem('xp-mode')||'Idle';mode.onchange=e=>{localStorage.setItem('xp-mode',e.target.value);setCaption('MODE: '+e.target.value.toUpperCase())}}if(k==='system'){const t=await window.xpDesktop.telemetry();sysPanel.innerHTML=`CPU ${t.cpu}%<br>RAM ${t.ram}%<br>DISK ${t.disk}%<br>UPTIME ${fmtUp(t.uptime)}<br>XP CORE ${t.core.online?'ONLINE':'OFFLINE'}`}});
close.onclick=()=>panel.classList.add('hidden');fullscreen.onclick=async()=>{await window.xpDesktop.toggleFullscreen();options.classList.add('hidden')};document.addEventListener('keydown',e=>{if(e.key==='Escape'){panel.classList.add('hidden');options.classList.add('hidden')}if(e.key==='F11')window.xpDesktop.toggleFullscreen()});
refresh();setInterval(refresh,3000);